// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;
    

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmC7tsnMhU5d50JD6Vs5gK8hl4Rkk6NuA',
    appId: '1:1019957040155:web:b83c427e187b11dbfcd4be',
    messagingSenderId: '1019957040155',
    projectId: 'ticketflix-backend',
    authDomain: 'ticketflix-backend.firebaseapp.com',
    databaseURL: 'https://ticketflix-backend-default-rtdb.firebaseio.com',
    storageBucket: 'ticketflix-backend.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWf6nLOc9A5zmF2vX9K83DJS2njpx3cM4',
    appId: '1:1019957040155:android:6bb740bd9f8fe474fcd4be',
    messagingSenderId: '1019957040155',
    projectId: 'ticketflix-backend',
    databaseURL: 'https://ticketflix-backend-default-rtdb.firebaseio.com',
    storageBucket: 'ticketflix-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpfMaCGGHHa2Rlwk74bicGQhSyS7P3000',
    appId: '1:1019957040155:ios:84c036df1a264bbcfcd4be',
    messagingSenderId: '1019957040155',
    projectId: 'ticketflix-backend',
    databaseURL: 'https://ticketflix-backend-default-rtdb.firebaseio.com',
    storageBucket: 'ticketflix-backend.appspot.com',
    iosClientId: '1019957040155-437ve1l5idq7no2sl1j4amr3s66cburn.apps.googleusercontent.com',
    iosBundleId: 'com.example.ticketflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpfMaCGGHHa2Rlwk74bicGQhSyS7P3000',
    appId: '1:1019957040155:ios:9b6e5b4b2b398e36fcd4be',
    messagingSenderId: '1019957040155',
    projectId: 'ticketflix-backend',
    databaseURL: 'https://ticketflix-backend-default-rtdb.firebaseio.com',
    storageBucket: 'ticketflix-backend.appspot.com',
    iosClientId: '1019957040155-dq7kl3e0setl6d9o2b6e0equf6gljask.apps.googleusercontent.com',
    iosBundleId: 'com.example.ticketflix.RunnerTests',
  );
}
